---
title: 'Meta-Analysis: Red Snapper in the Gulf of Mexico'
author: "Group 3"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library setup, include=FALSE,results="hide"}
library(tidyverse)
library(plotrix) #for quick s.e. calculations sometimes needed for data tidy step
library(meta) #nice package for most meta-statistics
library(DT)
library(tidyverse)
library(PRISMAstatement)
```


#### 1) Search terms
Searches were done using Web of Science.
```{r Search Terms, warning=FALSE, message=FALSE, fig.width=6}
searchTerms <- read_csv("search_terms.csv")
datatable(searchTerms)

```



#### 2) Prisma graphic

```{r Prisma, fig.keep='all',warning=FALSE, message=FALSE, fig.width=5}
prisma(found = 118,
       found_other = 11,
       no_dupes = 113, 
       screened = 113, 
       screen_exclusions = 87, 
       full_text = 26,
       full_text_exclusions = 14, 
       qualitative = 12, 
       quantitative = 0,
       width = 600, height = 600)

```




#### 3) Reasons for paper eliminations
```{r Table of paper exclusions}
paperReasons <- read_csv("paper_reasons.csv")
datatable(paperReasons)
```



Histogram of the reasons for excluding papers:

```{r Plot Exclusions,results="hide", fig.keep='all',warning=FALSE, message=FALSE}
ggplot(paperReasons, aes(Reason, Papers)) + geom_bar(stat = "identity") + coord_flip()

```



#### 4) Import the meta analysis table

```{r import metadata,  results="hide"}
data <- read_csv("meta-analysis_data.csv")
datatable(data)

```


A range of drivers were investigated:

```{r plot by driver, results="hide"}

data.simple <- data %>% group_by(Driver) %>% count()
ggplot(na.omit(data.simple), aes(Driver, n)) + geom_bar(stat = "identity") + coord_flip()

```
# ```{r plot by driver, results="hide"}
# uniqueStudy <- unique(data$Paper_ID)
# data.simple <- data[uniqueStudy,:] %>% group_by(Driver) %>% count()
# ggplot(na.omit(data.simple), aes(Driver, n)) + geom_bar(stat = "identity") + coord_flip()
# 
# ```

Three main study types were represented:


```{r plot by study type,  results="hide"}
data.simple <- data %>% group_by(StudyType) %>% count()
ggplot(na.omit(data.simple), aes(StudyType, n)) + geom_bar(stat = "identity") + coord_flip()

```

Age classes and definitions varied: 

```{r plot by age class, results="hide"}

data$Age_class[grep('juvenile',data$Age_class)] <- 'Juvenile'
data.simple <- data %>% group_by(Age_class) %>% count()

ggplot(na.omit(data.simple), aes(Age_class, n)) + geom_bar(stat = "identity") + coord_flip()

```

#### 5) Effect sizes

```{r Estimate effect size by driver, results="hide"}
treedata <- data %>% group_by(Driver) %>% summarise(mean.EffectSize_d = mean(EffectSize_d),
                                                    error = std.error(EffectSize_d))
```

```{r, Forest plot}
m <- metagen(mean.EffectSize_d, error, studlab = Driver, data = treedata) #fit generic meta-analysis to an object

#viz (draw a standard forest plot or metaregression plot)
forest(m,leftcols = "Driver",rightcols = c("effect", "ci"), fontsize=10) #grid-based graphics so a bit of work to resize
```

