---
title: "Project #3 - Meta-analysis Step #2"
author: "adellapa"
date: "2017"
output:
  html_document:
    theme: yeti
  pdf_document:
    toc: yes
   
---


###Step 2. Sort  
We searched our returned hits for appropriate studies that satisfied the criteria that we listed a priori. Typically, there are a set of simple assumptions for exclusion criteria for a meta-analysis in evidence-based research. Not a review, includes terms and actually studied the process at hand, and not a duplicate. Those are the three most common reasons for exclusion for the first round of exclusion.  The second round shifts from abstract/overview review and sorting of studies to detailed evidence extraction. Within this round, the most common reason for exclusion is lack of open data. 

###Prisma
We used the [PRISMA (Preferred Reporting Items for Systematic Reviews and Meta-Analyses)](http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1000097) statement/report as our mechanism to summarize our workflow criteria.


```{r PRIMSA, warning=FALSE, message=FALSE}
library(tidyverse)
library(PRISMAstatement)
prisma(found = 118,
       found_other = 11,
       no_dupes = 113, 
       screened = 113, 
       screen_exclusions = 87, 
       full_text = 26,
       full_text_exclusions = 14, 
       qualitative = 12, 
       quantitative = 0,
       width = 800, height = 800)



```
<br>  

###Exercise
Use your previous search and select a reasonable set of studies to explore the importance of general versus specific exclusion criteria on processing primary research literature as a synthesis substrate. As an important consideration here, please also try the second round, even briefly, for those not immediately excluded by adding another vector in your dataframe indicating whether useable data are available/provided within the publication. For the purposes of this sort step, the data can be a list, table, or even figure that shows means, variances, and sample sizes for every treatment level needed in the synthesis.

###Conclusions
1. A PRISMA statement is similar to a decision tree/workflow diagram and a recommended tool to summarize the synthesis process from primary research objects including publication and datasets (although typically publications).  
2. The sort process is best conceptualized as a two-step process.  
3. The first round of exclusions include reviews, terms listed by not studied, and duplicates.  
4. The second round of exclusions is typically associated with full publication review and included the former two criteria from the previous step but now adds in an estimate of likelihood that data are available for detailed synthesis.  
5. If there are two few studies with available data for synthesis (from within each study), typically defined as < 10 independent studies, then the jedi synthesis researcher can elect to shift to systematic review and summarize the research landscape of studies without **detailed analysis of strength of evidence from within studies**.

###Additional resources
Even if you never want to engage in these forms of synthesis, ensure you primary research publications are available to others by embracing the principles of open science and [effective scientific reporting](http://onlinelibrary.wiley.com/wol1/doi/10.1111/2041-210X.12758/full).  
A [step-by-step guide](http://www.ccace.ed.ac.uk/research/software-resources/systematic-reviews-and-meta-analyses) to the meta versus systematic review decision.  
The PRISMA flow diagram is required by many journals when submitting a systematic review or meta-analysis. However, several journals including PLOS ONE and PeerJ also require the [PRISMA Checklist (available for donload from site)](http://www.prisma-statement.org) as a supplemental file.