---
title: "Big Picture Flow"
author: "Cassie Glaspie"
date: "July 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}

library(diagram)

```

```{r}
par(mfrow=c(1,1))
# creates an empty plot
openplotmat()
 
# create the coordinates
pos <- coordinates(c(1,3,3,3,3))
pos

class(pos)
 
plot(pos, type = 'n')
text(pos)
```

## Adding arrows


```{r}
par(mar = rep(1, 4))
openplotmat()
pos <- coordinates(c(1,3,3,3,3))
# the dd parameter was used to move the segment arm
straightarrow(from = pos[1, ], to = pos[2, ])
straightarrow(from = pos[1, ], to = pos[4, ])
straightarrow(from = pos[2, ], to = pos[5, ])
straightarrow(from = pos[4, ], to = pos[7, ])
straightarrow(from = pos[4, ], to = pos[6, ])
straightarrow(from = pos[7, ], to = pos[10, ])
straightarrow(from = pos[5, ], to = pos[8, ])
straightarrow(from = pos[6, ], to = pos[7, ])
straightarrow(from = pos[10, ], to = pos[12, ])
straightarrow(from = pos[8, ], to = pos[12, ])

```

## Making captions

```{r}
txt1=paste("Environmental\ndrivers of snapper?")
txt2=paste("What do we know?")
txt3=paste("What do the\ndata tell us?")
txt4=paste("Systematic review\nand meta-analysis")
txt5=paste("Statistical models\n(SEAMAP data)")
txt6=paste("Processing\nNOAA data")
txt7=paste("Identify gaps in\nmonitoring")
txt8=paste("Identify gaps in\nknowledge")
txt9=paste("Identify new\nopportunities")

```
## Adding boxes

```{r}
my_label <- c(txt1, txt2, txt3, txt4, txt5, txt6, txt7, txt8, txt9)
my_text_size <- 1.3
my_edge_length <- 0.08

textrect(mid = pos[1,], radx = 0.12, rady = 0.08, lab = my_label[1], cex = my_text_size, box.col = "lightblue")
textrect(mid = pos[2,], radx = 0.12, rady = 0.06, lab = my_label[2], cex = my_text_size, box.col = "lightblue")
textrect(mid = pos[4,], radx = 0.12, rady = 0.06, lab = my_label[3], cex = my_text_size, box.col = "lightblue")
textrect(mid = pos[5,], radx = 0.12, rady = 0.06, lab = my_label[4], cex = my_text_size, box.col = "lightblue")
textrect(mid = pos[7,], radx = 0.10, rady = 0.06, lab = my_label[5], cex = my_text_size, box.col = "lightblue")
textrect(mid = pos[6,], radx = 0.08, rady = 0.06, lab = my_label[6], cex = my_text_size, box.col = "lightblue")
textrect(mid = pos[10,], radx = 0.12, rady = 0.06, lab = my_label[7], cex = my_text_size, box.col = "lightblue")
textrect(mid = pos[8,], radx = 0.12, rady = 0.06, lab = my_label[8], cex = my_text_size, box.col = "lightblue")
textrect(mid = pos[12,], radx = 0.12, rady = 0.06, lab = my_label[9], cex = my_text_size, box.col = "lightblue")

```
